version: 3

dotenv:
  - .env.devops

env:
  NODE_ENV: development
  COOKIE_SECRET: unsecure

tasks:
  terraform:
    cmds:
      - terraform -chdir=deploy {{.CLI_ARGS}}
  test:
    env:
      DB_LOCATION: ":memory:"
    cmds:
      - npm test
      - npx playwright test
  dev:
    env:
      PORT: 3000
      DB_LOCATION: ./modules/database/db.sqlite3
    cmds:
      - npm install
      - npm run dev
  db:pull:
    env:
      DB_LOCATION: ./modules/database/db.sqlite3
    cmds:
      - rm -rf ./tmp
      - litestream restore -config ./deploy/litestream.yml $DB_LOCATION
  deploy:
    silent: true
    cmds:
      - echo Will deploy to $SERVER_IP
      - rsync -a --exclude '.env.devops' ./ devops@$SERVER_IP:/home/devops/latest
      - ssh devops@$SERVER_IP "DOMAIN=https://dev.club R2_BACKUP_ENDPOINT=$R2_BACKUP_ENDPOINT R2_BACKUP_BUCKET=$R2_BACKUP_BUCKET R2_BACKUP_KEY=$R2_BACKUP_KEY R2_BACKUP_SECRET=$R2_BACKUP_SECRET bash -s" < ./deploy/deploy.sh
