version: 3

dotenv:
  - .env

env:
  NODE_ENV: development

tasks:
  test:
    env:
      DB_LOCATION: ":memory:"
    cmds:
      - npm test
      - npx playwright test
  dev:
    env:
      PORT: 3000
      DB_LOCATION: "{{.HOME}}/db.sqlite3"
    cmds:
      - npm install
      - npm run dev
  dev:tailwind:
    cmds:
      - npm run dev:tailwind
  db:pull:
    silent: true
    env:
      DB_BACKUP: "{{.HOME}}/backup"
      DB_LOCATION: "{{.HOME}}/db.sqlite3"
    cmds:
      - echo ⏳ Pulling DB backup from $SERVER_IP into $DB_BACKUP...
      - rm -rf $DB_LOCATION
      - rm -rf $DB_BACKUP && mkdir $DB_BACKUP
      - rsync -a --exclude 'lost+found' devops@$SERVER_IP:/mnt/backup/ $DB_BACKUP
      - litestream restore -config ./modules/database/litestream.yml $DB_LOCATION
  infra:
    cmds:
      - npm run infra
  deploy:
    silent: true
    cmds:
      - echo ⏳ Building assets...
      - npm run build
      - echo ⏳ Preparing to deploy to $SERVER_IP...
      - rsync -a --exclude 'node_modules' --exclude 'test_results' ./ devops@$SERVER_IP:/home/devops/latest
      - ssh devops@$SERVER_IP "DOMAIN=$DOMAIN bash < /home/devops/latest/deploy/deploy.sh"
