version: 3

dotenv:
  - .env

env:
  NODE_ENV: development
  COOKIE_SECRET: unsecure

tasks:
  test:
    env:
      DB_LOCATION: ":memory:"
    cmds:
      - npm test
      - npx playwright test
  dev:
    env:
      PORT: 3000
      DB_LOCATION: ./modules/database/db.sqlite3
    cmds:
      - npm install
      - npm run dev
  db:pull:
    env:
      DB_LOCATION: ./modules/database/db.sqlite3
    cmds:
      - rm -rf ./backup
      - scp -r devops@$SERVER_IP:/mnt/backup ./backup
      - litestream restore -o $DB_LOCATION ./backup
  deploy:infra:
    cmds:
      - npm run infra
  deploy:
    silent: true
    cmds:
      - echo Will deploy to $SERVER_IP
      - rsync -a --exclude 'node_modules' --exclude 'deploy' --exclude 'db.sqlite3*' ./ devops@$SERVER_IP:/home/devops/latest
      - ssh devops@$SERVER_IP "DOMAIN=$DOMAIN bash -s" < ./deploy/deploy.sh
