version: 3

dotenv:
  - .env

env:
  NODE_ENV: development

tasks:
  test:
    env:
      DB_LOCATION: ":memory:"
    cmds:
      - npm test
      - npx playwright test
  dev:
    env:
      PORT: 3000
      DB_LOCATION: ~/db.sqlite3
    cmds:
      - npm install
      - npm run dev
  db:pull:
    env:
      DB_LOCATION: ~/db.sqlite3
    cmds:
      - rm -rf ./backup
      - scp -r devops@$SERVER_IP:/mnt/backup ./backup
      - litestream restore -o $DB_LOCATION ./backup
  infra:
    cmds:
      - npm run infra
  deploy:
    cmds:
      - rsync -a --exclude 'node_modules' ./ devops@$SERVER_IP:/home/devops/latest
      - ssh devops@$SERVER_IP "DOMAIN=$DOMAIN bash -s" < ./deploy/deploy.sh
