#cloud-config
users:
  - name: devops
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${publicKey}
packages:
  - htop
  - jq
  - fail2ban
package_update: true
package_upgrade: true
package_reboot_if_required: true
write_files:
  - path: /etc/ssh/sshd_config.d/ssh-hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      ChallengeResponseAuthentication no
      MaxAuthTries 3
      AllowTcpForwarding no
      X11Forwarding no
      AllowAgentForwarding no
      AuthorizedKeysFile .ssh/authorized_keys
      AllowUsers devops
      AcceptEnv CI_*
  - path: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled = true
      banaction = iptables-multiport
runcmd:
  # Bug, see https://github.com/hetznercloud/terraform-provider-hcloud/issues/473
  - udevadm trigger -c add -s block -p ID_VENDOR=HC --verbose -p ID_MODEL=Volume

  # Symlinks to volumes
  - ln -s /mnt/HC_Volume_${backupVolumeId} /mnt/backup

  - systemctl daemon-reload
  - systemctl enable fail2ban
  - systemctl reload ssh
